### ISSUE TITLE
Bug: does not work when new design interface is localized

### ISSUE THREAD

**Issue by Jackymancs4** [pauldraper/unreddit#1]
Hello @pauldraper 
Thanks for this extension.

Right now, it doesn't work when the new design interface is localized in a language different from English.

E.g. In italian (my language) `Comment removed by moderator` is always written down as `[rimosso]`.

It seems to work fine, fine 

I think the problem is here
https://github.com/pauldraper/unreddit/blob/4f22e1cb287fa8e0d7216b6db8db816f635c60a2/chrome/content.js#L15

where you hard-coded the english string.

I have not thoroughly investigated into your code, and I'm not sure how you could think a more general approach, since in the new design css classes are quite random, but just adding a note about it in the description would be a start.

**Comment by pauldraper** [comment]
Yes, that is indeed a good summary of the problem.

Unfortunately I do not see an easy solution.

**Comment by pauldraper** [comment]
I have documented this so users are aware (and perhaps can suggest a fix).
